name: 'update-ietf-draft-tasks-action'
description: 'Installs make, validate, export tasks for IETF Draft repo'

inputs:
  release-version:
    description: 'Git ref of create-ietf-draft-repo-action to use (eg. v0.1.1). Defaults to main'
    default: main

runs:
  using: 'composite'
  steps:
    - id: checkout-create-repo
      uses: actions/checkout@v3
      with:
        repository: 'IRTF-HRPC/create-ietf-draft-repo-action'
        ref: ${{ inputs.release-version }}
        path: create-ietf-draft-repo-action

    - id: copy-latest-task-workflows
      shell: bash
      run: |
        mkdir -p update-tasks-action/.github/workflows/
        cp -r create-ietf-draft-repo-action/workflows/* update-tasks-action/.github/workflows/

    - id: push-changes
      shell: bash
      working-directory: update-tasks-action
      run: |
        RELEASE_VERSION=${{ inputs.release-version }}
        if [ -z "$RELEASE_VERSION" ]; then
          RELEASE_VERSION="main"
        fi

        git status
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add workflows/
        git commit -m "update task workflows to version at $RELEASE_VERSION"
        git push
